.MODEL SMALL

;! DISPLAYING DISCOUNTED OPTION DUE TO PROXIMITY TAKEN FROM INSIDE CART.ASM

; CHECKOUT.ASM
; TURNS THE CART FROM CART.ASM INTO A SAVED ORDER, AND LETS THE
; USER LOOK BACK AT EVERYTHING THEY'VE ORDERED SO FAR.
;
;   CHECKOUTMODULE  - CALLED FROM CARTMODULE (VIEW CART) AFTER THE
;                     USER HAS ALREADY ANSWERED "CHECKOUT NOW? (Y/N)"
;                     OVER THERE. IT DOES NOT ASK AGAIN - IT SHOWS A
;                     RECEIPT WITH TAX AND ANY PROXIMITY DISCOUNT,
;                     TAKES PAYMENT (COD OR CARD - CARD ASKS FOR THE
;                     CARDHOLDER NAME, CARD NUMBER AND 3-DIGIT CVV,
;                     EACH RE-ASKED UNTIL VALID), SHOWS THE ADDRESS
;                     ON FILE FOR THE LOGGED-IN ACCOUNT (SEE
;                     CURRENT_ADDR IN LOGIN.ASM) WITH AN ESTIMATED
;                     DELIVERY TIME, SAVES THE ORDER INTO HISTORY,
;                     THEN EMPTIES THE CART.
;   HISTORYMODULE   - CALLED FROM MAIN.ASM'S "3. ORDER HISTORY".
;                     LISTS EVERY ORDER CHECKOUTMODULE HAS SAVED,
;                     THEN A GRAND TOTAL ACROSS ALL OF THEM.

PUBLIC CHECKOUTMODULE, HISTORYMODULE

; CART ITEMS ORDER QUANTITY LIVES IN CART.ASM ITEM'S QUANTITY IS ONLY BORROW IT HERE.
EXTRN QTY_BURGER:BYTE, QTY_NASI:BYTE, QTY_RICE:BYTE, QTY_CHICKEN:BYTE
EXTRN TOTAL_PRICE:WORD
EXTRN DISCOUNT_TOTAL:WORD           ; FROM CART.ASM - RM SAVED VIA THE PROXIMITY DISCOUNT
EXTRN PRINT_NUM:NEAR                ; FROM TOOLS.ASM - SHARED NUMBER-PRINTING HELPER
EXTRN PRINT_STRING:NEAR             ; FROM TOOLS.ASM - SHARED STRING-PRINTING HELPER
EXTRN CHECK_ALPHA:NEAR, CHECK_DIGITS:NEAR   ; FROM TOOLS.ASM

; FROM LOGIN.ASM
EXTRN CURRENT_ADDR:BYTE             ; THE LOGGED-IN ACCOUNT'S SAVED DELIVERY ADDRESS

; FROM TOOLS.ASM
EXTRN READNUM:NEAR, NEWLINE:NEAR, READSTRING:NEAR

.DATA
    ; C++ EQUIVALENT: #DEFINE MAX_HISTORY 10
    MAX_HISTORY      EQU 10          ; NUMBER OF PAST ORDERS TO KEEP
    TAX_PERCENTAGE   EQU 6           ; FLAT TAX RATE APPLIED TO THE SUBTOTAL

    ; ---------- INPUT LENGTH LIMITS (ALSO USED TO VALIDATE INPUT) ----------
    NAME_MAXLEN      EQU 30          ; MAX CHARACTERS FOR CARDHOLDER NAME

    ;! just only card length of 12 digits total no need to do 16 digits
    CARD_MINLEN      EQU 12          ; SHORTEST CARD NUMBER WE ACCEPT
    CARD_MAXLEN      EQU 16          ; LONGEST CARD NUMBER WE ACCEPT
    CVV_MAXLEN       EQU 3           ; CVV IS ALWAYS EXACTLY 3 DIGITS

    ; ---------- CHECKOUT SCREEN TEXT ----------
    CHECKOUT_HEADER  DB 0DH,0AH,0DH,0AH,'==================================',0DH,0AH
                     DB                 '             CHECKOUT             ',0DH,0AH
                     DB                 '==================================',0DH,0AH,'$'

    EMPTY_CART_MSG   DB 0DH,0AH,'YOUR CART IS EMPTY - ADD SOMETHING FIRST!',0DH,0AH,'$'
    HISTORY_FULL_MSG DB 0DH,0AH,'(ORDER HISTORY IS FULL, SO THIS ORDER WILL NOT BE SAVED THERE.)',0DH,0AH,'$'
    SUCCESS_MSG      DB 0DH,0AH,'ORDER PLACED! THANKS FOR ORDERING.',0DH,0AH,'$'
    PAUSE_MSG        DB 0DH,0AH,0DH,0AH,'PRESS ANY KEY TO CONTINUE...$'

    ; ITEM LINES SHARED BY THE CHECKOUT RECEIPT AND THE ORDER HISTORY LIST
    CO_BURGER        DB 0DH,0AH,'BURGER X $'
    CO_NASI          DB 0DH,0AH,'NASI LEMAK X $'
    CO_RICE          DB 0DH,0AH,'EGG FRIED RICE X $'
    CO_CHICKEN       DB 0DH,0AH,'2PCS FRIED CHICKEN X $'
    CO_TOTAL         DB 0DH,0AH,'TOTAL: RM $'

    ; ---------- RECEIPT: SUBTOTAL, DISCOUNT, TAX, AMOUNT DUE ----------
    ; SEPARATES THE ITEM LIST ABOVE FROM THE SUBTOTAL/DISCOUNT/TAX/TOTAL
    ; SUMMARY BELOW, SAME DASHED-LINE STYLE AS CART.ASM'S TOTAL PRICE LINE
    RECEIPT_SEPARATOR DB 0DH,0AH,0DH,0AH,'----------------------------------',0DH,0AH,'$'
    SUBTOTAL_LABEL   DB 'SUBTOTAL: RM $'
    DISCOUNT_LABEL   DB 0DH,0AH,'PROX. DISCOUNT: -RM $'
    TAX_LABEL        DB 0DH,0AH,'TAX (6%): RM $'
    TOTAL_DUE_LABEL  DB 0DH,0AH,0DH,0AH,'TOTAL DUE: RM $'

    ORDER_SUBTOTAL   DW 0     ; ITEM TOTAL BEFORE ANY TAX OR DISCOUNT
    ORDER_TAX        DW 0     ; TAX ON THE ORDER BEING CHECKED OUT RIGHT NOW
    ORDER_DUE        DW 0     ; SUBTOTAL - DISCOUNT + TAX = WHAT THE CUSTOMER MUST PAY

    ; ---------- PAYMENT ----------
    PAYMENT_MENU_MSG    DB 0DH,0AH,0DH,0AH,'HOW WILL YOU PAY?',0DH,0AH
                        DB '1. CASH ON DELIVERY (COD)',0DH,0AH
                        DB '2. CARD',0DH,0AH
                        DB 'CHOOSE AN OPTION: $'
    INVALID_PAYMENT_MSG DB 0DH,0AH,'INVALID CHOICE, TRY AGAIN.',0DH,0AH,'$'

    CASH_PROMPT         DB 0DH,0AH,'ENTER CASH AMOUNT FOR COD (RM): $'
    CHANGE_LABEL        DB 0DH,0AH,'CHANGE: RM $'
    INSUFFICIENT_MSG    DB 0DH,0AH,'THAT IS NOT ENOUGH CASH - CHECKOUT CANCELLED.',0DH,0AH,'$'
    CARD_APPROVED_MSG   DB 0DH,0AH,'CARD PAYMENT APPROVED.',0DH,0AH,'$'

    CASH_TENDERED       DW 0             ; CASH THE CUSTOMER HANDED OVER
    CHANGE_DUE           DW 0             ; CASH_TENDERED - ORDER_DUE

    ; ---------- CARD DETAILS (ASKED FOR CARD PAYMENTS ONLY) ----------
    NAME_PROMPT          DB 0DH,0AH,'ENTER CARDHOLDER NAME: $'
    INVALID_NAME_MSG     DB 0DH,0AH,'INVALID NAME - LETTERS AND SPACES ONLY, TRY AGAIN.',0DH,0AH,'$'
    CARD_NUMBER_PROMPT   DB 0DH,0AH,'ENTER CARD NUMBER (12-16 DIGITS): $'
    INVALID_CARD_MSG     DB 0DH,0AH,'INVALID CARD NUMBER - DIGITS ONLY, 12-16 OF THEM, TRY AGAIN.',0DH,0AH,'$'
    CVV_PROMPT           DB 0DH,0AH,'ENTER THE 3-DIGIT CVV (ON THE BACK OF THE CARD): $'
    INVALID_CVV_MSG      DB 0DH,0AH,'INVALID CVV - MUST BE EXACTLY 3 DIGITS, TRY AGAIN.',0DH,0AH,'$'

    ; DOS BUFFERED-INPUT FORMAT: BYTE0 = MAX CHARS, BYTE1 = ACTUAL CHARS
    ; TYPED (FILLED IN BY READSTRING), BYTE2.. = THE CHARACTERS.
    ; DOS NEEDS ROOM FOR THE CR TOO, SO THE MAX BYTE IS MAXLEN+1
    NAME_BUF          DB NAME_MAXLEN+1, 0, NAME_MAXLEN+2 DUP(0)
    CARD_NUMBER_BUF   DB CARD_MAXLEN+1, 0, CARD_MAXLEN+2 DUP(0)
    CVV_BUF           DB CVV_MAXLEN+1, 0, CVV_MAXLEN+2 DUP(0)

    ; ---------- DELIVERY (SHOWN AFTER EITHER PAYMENT METHOD) ----------
    ; No longer asked for - it's just wherever the logged-in account
    ; has on file (CURRENT_ADDR, from login.asm).
    DELIVERY_TO_MSG         DB 0DH,0AH,0DH,0AH,'DELIVERING TO: $'
    DELIVERY_ESTIMATE_MSG  DB 0DH,0AH,'ESTIMATION OF DELIVERY: 30MIN',0DH,0AH,'$'

    ; ---------- ORDER HISTORY STORAGE ----------
    ; SLOT I (0 .. HISTORY_COUNT-1) HOLDS ONE PAST CHECKOUT
    ; ARRAY TYPE IN ASM, 
    HIST_BURGER   DB MAX_HISTORY DUP(0)
    HIST_NASI     DB MAX_HISTORY DUP(0)
    HIST_RICE     DB MAX_HISTORY DUP(0)
    HIST_CHICKEN  DB MAX_HISTORY DUP(0)
    HIST_TOTAL    DW MAX_HISTORY DUP(0)     ; FINAL AMOUNT ACTUALLY PAID (TAX INCLUDED)
    HISTORY_COUNT DW 0

    ; ---------- ORDER HISTORY SCREEN TEXT ----------
    HISTORY_HEADER    DB 0DH,0AH,'==================================',0DH,0AH
                      DB          '           ORDER HISTORY          ',0DH,0AH
                      DB          '==================================',0DH,0AH,'$'
    HISTORY_EMPTY_MSG DB 0DH,0AH,'NO ORDERS YET - CHECKOUT YOUR CART TO SEE IT HERE.',0DH,0AH,'$'
    ORDER_LABEL       DB 0DH,0AH,0DH,0AH,'ORDER #$'
    SEPARATOR_MSG     DB 0DH,0AH,'----------------------------------',0DH,0AH,'$'
    GRAND_TOTAL_MSG   DB 0DH,0AH,'GRAND TOTAL (ALL ORDERS): RM $'

    GRAND_TOTAL       DW 0          ; SUM OF EVERY PAST ORDER'S TOTAL, FOR HISTORYMODULE

.CODE

EXTRN CLEARSCREEN:NEAR

; =============================================================
; CHECKOUTMODULE
; SHOWS A RECEIPT (ITEMS, SUBTOTAL, DISCOUNT, TAX, TOTAL DUE),
; TAKES PAYMENT, THEN COPIES THE ORDER INTO HISTORY AND EMPTIES
; THE CART. THE CALLER (CARTMODULE) IS THE ONE THAT ALREADY
; CONFIRMED "CHECKOUT NOW? (Y/N)" WITH THE USER.
; =============================================================
CHECKOUTMODULE PROC NEAR

    CMP WORD PTR TOTAL_PRICE, 0
    JNE CO_SHOW_RECEIPT
    LEA DX, EMPTY_CART_MSG
    CALL PRINT_STRING
    CALL CO_WAIT_KEY
    RET

CO_SHOW_RECEIPT:
    CALL CLEARSCREEN
    LEA DX, CHECKOUT_HEADER
    CALL PRINT_STRING

    CALL CO_PRINT_ITEMS          ; PRINTS THE 4 LIVE CART QUANTITIES

    LEA DX, RECEIPT_SEPARATOR
    CALL PRINT_STRING

    CALL CO_CALC_TAX             ; FILLS IN ORDER_SUBTOTAL, ORDER_TAX AND ORDER_DUE

    LEA DX, SUBTOTAL_LABEL       ; RAW ITEM TOTAL - NO TAX, NO DISCOUNT YET
    CALL PRINT_STRING
    MOV AX, ORDER_SUBTOTAL
    CALL PRINT_NUM

    CMP WORD PTR DISCOUNT_TOTAL, 0
    JE  CO_NO_DISCOUNT_LINE
    LEA DX, DISCOUNT_LABEL
    CALL PRINT_STRING
    MOV AX, DISCOUNT_TOTAL
    CALL PRINT_NUM
CO_NO_DISCOUNT_LINE:

    LEA DX, TAX_LABEL
    CALL PRINT_STRING
    MOV AX, ORDER_TAX
    CALL PRINT_NUM

    LEA DX, TOTAL_DUE_LABEL      ; SUBTOTAL - DISCOUNT + TAX, ALL ADDED TOGETHER
    CALL PRINT_STRING
    MOV AX, ORDER_DUE
    CALL PRINT_NUM

    CALL CO_TAKE_PAYMENT         ; ASKS COD/CARD, SHOWS CHANGE IF PAYING COD
    CMP AL, 1                    ; AL = 1 IF PAYMENT WENT THROUGH, 0 IF NOT ENOUGH CASH
    JE  CO_SHOW_DELIVERY

    LEA DX, INSUFFICIENT_MSG
    CALL PRINT_STRING
    CALL CO_WAIT_KEY
    RET

CO_SHOW_DELIVERY:                 ; PAYMENT WENT THROUGH - SHOW WHERE IT'S GOING
    LEA DX, DELIVERY_TO_MSG
    CALL PRINT_STRING
    LEA DX, CURRENT_ADDR
    CALL PRINT_STRING

    LEA DX, DELIVERY_ESTIMATE_MSG
    CALL PRINT_STRING

CO_SAVE_ORDER:
    MOV AX, HISTORY_COUNT
    CMP AX, MAX_HISTORY
    JL  CO_STORE

    LEA DX, HISTORY_FULL_MSG     ; HISTORY FULL - STILL CHECKOUT, JUST SKIP SAVING IT
    CALL PRINT_STRING
    JMP CO_CLEAR_CART

CO_STORE:
    ; BX = WHICH HISTORY SLOT (0, 1, 2, ...) THIS ORDER GOES INTO.
    ; HIST_BURGER/NASI/RICE/CHICKEN ARE 1 BYTE PER SLOT, SO "SLOT
    ; NUMBER" AND "BYTE OFFSET" ARE THE SAME THING FOR THEM - JUST
    ; ADD BX. HIST_TOTAL IS DIFFERENT (SEE THE SHL BELOW).
    MOV BX, HISTORY_COUNT        ; BX = INDEX OF THE NEW HISTORY SLOT

    LEA SI, HIST_BURGER
    ADD SI, BX
    MOV AL, QTY_BURGER
    MOV [SI], AL

    LEA SI, HIST_NASI
    ADD SI, BX
    MOV AL, QTY_NASI
    MOV [SI], AL

    LEA SI, HIST_RICE
    ADD SI, BX
    MOV AL, QTY_RICE
    MOV [SI], AL

    LEA SI, HIST_CHICKEN
    ADD SI, BX
    MOV AL, QTY_CHICKEN
    MOV [SI], AL

    ; HIST_TOTAL HOLDS 2-BYTE NUMBERS (DW), NOT 1-BYTE (DB) LIKE THE
    ; ITEM COUNTS ABOVE, SO SLOT NUMBER 2 STARTS AT BYTE 4, NOT BYTE
    ; 2. "SHL DI, 1" IS JUST A FAST WAY OF WRITING "DI = DI * 2".
    MOV DI, BX
    SHL DI, 1                    ; HIST_TOTAL HOLDS WORDS, SO INDEX*2
    LEA SI, HIST_TOTAL
    ADD SI, DI
    MOV AX, ORDER_DUE            ; SAVE WHAT WAS ACTUALLY CHARGED (TAX INCLUDED)
    MOV [SI], AX

    INC HISTORY_COUNT

CO_CLEAR_CART:
    MOV QTY_BURGER, 0
    MOV QTY_NASI, 0
    MOV QTY_RICE, 0
    MOV QTY_CHICKEN, 0
    MOV WORD PTR TOTAL_PRICE, 0
    MOV WORD PTR DISCOUNT_TOTAL, 0

    LEA DX, SUCCESS_MSG
    CALL PRINT_STRING
    CALL CO_WAIT_KEY
    RET
CHECKOUTMODULE ENDP


; =============================================================
; HISTORYMODULE
; LISTS EVERY ORDER CHECKOUTMODULE HAS SAVED SO FAR, OLDEST FIRST,
; THEN A GRAND TOTAL ADDED UP ACROSS ALL OF THEM.
; =============================================================
HISTORYMODULE PROC NEAR
    MOV GRAND_TOTAL, 0           ; RESET IN CASE THIS GETS SHOWN MORE THAN ONCE

    LEA DX, HISTORY_HEADER
    CALL PRINT_STRING

    MOV CX, HISTORY_COUNT
    CMP CX, 0
    JNE HM_LIST
    LEA DX, HISTORY_EMPTY_MSG
    CALL PRINT_STRING
    JMP HM_DONE

HM_LIST:
    MOV BX, 0                    ; BX = INDEX OF THE ORDER BEING PRINTED

HM_LOOP:
    LEA DX, ORDER_LABEL
    CALL PRINT_STRING
    MOV AX, BX
    INC AX                       ; SHOW "ORDER #1", "ORDER #2", ... NOT #0
    CALL PRINT_NUM

    ; --- BURGER ---
    LEA DX, CO_BURGER
    CALL PRINT_STRING
    LEA SI, HIST_BURGER
    ADD SI, BX
    MOV AL, [SI]
    MOV AH, 0                    ; AL IS 0-255, SO WIDEN TO AX BEFORE PRINTING
    CALL PRINT_NUM

    ; --- NASI LEMAK ---
    LEA DX, CO_NASI
    CALL PRINT_STRING
    LEA SI, HIST_NASI
    ADD SI, BX
    MOV AL, [SI]
    MOV AH, 0
    CALL PRINT_NUM

    ; --- EGG FRIED RICE ---
    LEA DX, CO_RICE
    CALL PRINT_STRING
    LEA SI, HIST_RICE
    ADD SI, BX
    MOV AL, [SI]
    MOV AH, 0
    CALL PRINT_NUM

    ; --- FRIED CHICKEN ---
    LEA DX, CO_CHICKEN
    CALL PRINT_STRING
    LEA SI, HIST_CHICKEN
    ADD SI, BX
    MOV AL, [SI]
    MOV AH, 0
    CALL PRINT_NUM

    ; --- TOTAL (TAX ALREADY INCLUDED, SINCE THAT IS WHAT WAS CHARGED) ---
    LEA DX, CO_TOTAL
    CALL PRINT_STRING
    MOV DI, BX
    SHL DI, 1
    LEA SI, HIST_TOTAL
    ADD SI, DI
    MOV AX, [SI]
    CALL PRINT_NUM
    ADD GRAND_TOTAL, AX           ; FOLD THIS ORDER INTO THE RUNNING TOTAL

    LEA DX, SEPARATOR_MSG
    CALL PRINT_STRING

    INC BX
    CMP BX, HISTORY_COUNT
    JGE HM_TOTAL                 ; MASM CAN'T REACH HM_LOOP WITH A SHORT JL FROM
    JMP HM_LOOP                  ; HERE (LOOP BODY IS TOO LONG) - JMP HAS NO SUCH LIMIT

HM_TOTAL:
    LEA DX, GRAND_TOTAL_MSG
    CALL PRINT_STRING
    MOV AX, GRAND_TOTAL
    CALL PRINT_NUM

HM_DONE:
    CALL CO_WAIT_KEY
    RET
HISTORYMODULE ENDP

; =============================================================
; LOCAL HELPERS - SAME PATTERN AS CART.ASM'S OWN PRINT HELPERS,
; JUST KEPT PRIVATE TO THIS FILE (CHECKOUT.ASM) SO NOTHING OUTSIDE
; NEEDS TO KNOW THEY EXIST.
; =============================================================

; --- PRINTS THE 4 LIVE CART QUANTITIES (NO TOTAL - CHECKOUTMODULE
;     PRINTS SUBTOTAL/DISCOUNT/TAX/TOTAL DUE ITSELF, RIGHT AFTER
;     CALLING THIS) ---
CO_PRINT_ITEMS PROC NEAR
    LEA DX, CO_BURGER
    CALL PRINT_STRING
    MOV AL, QTY_BURGER
    MOV AH, 0                    ; AL IS 0-255, SO WIDEN TO AX BEFORE PRINTING
    CALL PRINT_NUM

    LEA DX, CO_NASI
    CALL PRINT_STRING
    MOV AL, QTY_NASI
    MOV AH, 0
    CALL PRINT_NUM

    LEA DX, CO_RICE
    CALL PRINT_STRING
    MOV AL, QTY_RICE
    MOV AH, 0
    CALL PRINT_NUM

    LEA DX, CO_CHICKEN
    CALL PRINT_STRING
    MOV AL, QTY_CHICKEN
    MOV AH, 0
    CALL PRINT_NUM
    RET
CO_PRINT_ITEMS ENDP

; --- WORKS OUT THE PRE-DISCOUNT SUBTOTAL, TAX AND TOTAL DUE.
;     TOTAL_PRICE (FROM CART.ASM) ALREADY HAS THE PROXIMITY DISCOUNT
;     BAKED IN (SEE CALC_PRICE IN CART.ASM), SO ADDING BACK
;     DISCOUNT_TOTAL RECOVERS THE ORIGINAL, UNDISCOUNTED SUBTOTAL.
;     TAX IS 6% OF THE POST-DISCOUNT AMOUNT (TOTAL_PRICE), ROUNDED
;     DOWN TO THE NEAREST RINGGIT. TOTAL DUE IS SUBTOTAL - DISCOUNT
;     + TAX, WHICH SINCE TOTAL_PRICE = SUBTOTAL - DISCOUNT, IS JUST
;     TOTAL_PRICE + TAX.
;
;     THIS ONE STILL HAS TO BE A REAL CALCULATION (NOT HARDCODED)
;     BECAUSE THE ORDER TOTAL CHANGES DEPENDING ON WHAT WAS ORDERED -
;     UNLIKE THE DISCOUNT IN CART.ASM, THERE'S NO FIXED LIST OF
;     "POSSIBLE TOTALS" TO PRE-CALCULATE.
;
;     WORKED EXAMPLE: 2 BURGERS AT A DISCOUNTED RM4 EACH (SEE
;     CALC_PRICE) MEANS TOTAL_PRICE = 8 AND DISCOUNT_TOTAL = 2
;     (RM1 SAVED PER BURGER). SO: SUBTOTAL = 8+2 = RM10, TAX = 8*6/100
;     = RM0 (ROUNDS DOWN), TOTAL DUE = 8+0 = RM8. ---
CO_CALC_TAX PROC NEAR
    PUSH BX
    PUSH DX

    MOV AX, TOTAL_PRICE
    ADD AX, DISCOUNT_TOTAL        ; AX = ORIGINAL, PRE-DISCOUNT SUBTOTAL
    MOV ORDER_SUBTOTAL, AX

    MOV AX, TOTAL_PRICE
    MOV BX, TAX_PERCENTAGE
    MUL BX                       ; DX:AX = TOTAL_PRICE * TAX_PERCENTAGE
                                  ; (E.G. RM8 * 6 = 48 - "6% OF RM8" AS A
                                  ; WHOLE NUMBER BEFORE WE DIVIDE BACK DOWN)
    MOV BX, 100
    DIV BX                       ; AX = TAX AMOUNT (48 / 100 = 0, ROUNDED DOWN)
    MOV ORDER_TAX, AX

    MOV AX, TOTAL_PRICE
    ADD AX, ORDER_TAX
    MOV ORDER_DUE, AX

    POP DX
    POP BX
    RET
CO_CALC_TAX ENDP

; --- ASKS COD OR CARD AND COLLECTS PAYMENT.
;     COD ALSO ASKS FOR THE CASH AMOUNT AND SHOWS CHANGE. CARD ASKS
;     FOR THE CARDHOLDER NAME, CARD NUMBER AND CVV (EACH RE-ASKED
;     UNTIL VALID).
;     RETURNS: AL = 1 IF PAYMENT WENT THROUGH, AL = 0 IF THE CASH
;              HANDED OVER WAS NOT ENOUGH (CHECKOUT IS CANCELLED). ---
CO_TAKE_PAYMENT PROC NEAR
CO_ASK_METHOD:
    LEA DX, PAYMENT_MENU_MSG
    CALL PRINT_STRING

    MOV AH, 01H                  ; READ ONE KEY (1 OR 2)
    INT 21H

    CMP AL, '1'
    JE  CO_PAY_CASH
    CMP AL, '2'
    JE  CO_PAY_CARD

    LEA DX, INVALID_PAYMENT_MSG
    CALL PRINT_STRING
    JMP CO_ASK_METHOD

CO_PAY_CARD:
    CALL CO_READ_NAME             ; CARDHOLDER NAME (LETTERS/SPACES ONLY)
    CALL CO_READ_CARDNUM          ; CARD NUMBER (12-16 DIGITS)
    CALL CO_READ_CVV              ; CVV (EXACTLY 3 DIGITS)

    LEA DX, CARD_APPROVED_MSG
    CALL PRINT_STRING
    MOV AL, 1
    RET

CO_PAY_CASH:
    LEA DX, CASH_PROMPT
    CALL PRINT_STRING
    CALL READNUM                 ; AX = CASH AMOUNT TYPED IN (FROM TOOLS.ASM)
    CALL NEWLINE
    MOV CASH_TENDERED, AX

    CMP AX, ORDER_DUE
    JGE CO_CASH_OK
    MOV AL, 0                    ; NOT ENOUGH CASH
    RET

CO_CASH_OK:
    SUB AX, ORDER_DUE
    MOV CHANGE_DUE, AX

    LEA DX, CHANGE_LABEL
    CALL PRINT_STRING
    MOV AX, CHANGE_DUE
    CALL PRINT_NUM

    MOV AL, 1
    RET
CO_TAKE_PAYMENT ENDP

; --- ASKS FOR THE CARDHOLDER NAME AND RE-ASKS UNTIL IT IS NOT
;     EMPTY AND CONTAINS ONLY LETTERS AND SPACES. FILLS NAME_BUF. ---
CO_READ_NAME PROC NEAR
CO_READ_NAME_AGAIN:
    LEA DX, NAME_PROMPT
    CALL PRINT_STRING
    LEA DX, NAME_BUF
    CALL READSTRING
    CALL NEWLINE

    MOV CL, NAME_BUF+1           ; ACTUAL NUMBER OF CHARACTERS TYPED
    XOR CH, CH
    LEA SI, NAME_BUF+2
    CALL CHECK_ALPHA
    CMP AL, 1
    JE  CO_READ_NAME_OK

    LEA DX, INVALID_NAME_MSG
    CALL PRINT_STRING
    JMP CO_READ_NAME_AGAIN

CO_READ_NAME_OK:
    RET
CO_READ_NAME ENDP

; --- ASKS FOR A CARD NUMBER AND RE-ASKS UNTIL IT IS CARD_MINLEN TO
;     CARD_MAXLEN DIGITS, DIGITS ONLY. FILLS CARD_NUMBER_BUF. ---
CO_READ_CARDNUM PROC NEAR
CO_READ_CARDNUM_AGAIN:
    LEA DX, CARD_NUMBER_PROMPT
    CALL PRINT_STRING
    LEA DX, CARD_NUMBER_BUF
    CALL READSTRING
    CALL NEWLINE

    MOV CL, CARD_NUMBER_BUF+1    ; ACTUAL NUMBER OF CHARACTERS TYPED
    XOR CH, CH
    CMP CX, CARD_MINLEN
    JB  CO_CARDNUM_INVALID

    LEA SI, CARD_NUMBER_BUF+2
    CALL CHECK_DIGITS
    CMP AL, 1
    JE  CO_READ_CARDNUM_OK

CO_CARDNUM_INVALID:
    LEA DX, INVALID_CARD_MSG
    CALL PRINT_STRING
    JMP CO_READ_CARDNUM_AGAIN

CO_READ_CARDNUM_OK:
    RET
CO_READ_CARDNUM ENDP

; --- ASKS FOR THE 3-DIGIT CVV AND RE-ASKS UNTIL IT IS EXACTLY
;     CVV_MAXLEN DIGITS, DIGITS ONLY. FILLS CVV_BUF. ---
CO_READ_CVV PROC NEAR
CO_READ_CVV_AGAIN:
    LEA DX, CVV_PROMPT
    CALL PRINT_STRING
    LEA DX, CVV_BUF
    CALL READSTRING
    CALL NEWLINE

    MOV CL, CVV_BUF+1            ; ACTUAL NUMBER OF CHARACTERS TYPED
    XOR CH, CH
    CMP CX, CVV_MAXLEN
    JNE CO_CVV_INVALID

    LEA SI, CVV_BUF+2
    CALL CHECK_DIGITS
    CMP AL, 1
    JE  CO_READ_CVV_OK

CO_CVV_INVALID:
    LEA DX, INVALID_CVV_MSG
    CALL PRINT_STRING
    JMP CO_READ_CVV_AGAIN

CO_READ_CVV_OK:
    RET
CO_READ_CVV ENDP

; --- CHECKS THAT CX CHARACTERS STARTING AT DS:SI ARE ALL '0'-'9'.
;     RETURNS AL = 1 IF SO (AND CX > 0), AL = 0 OTHERWISE. ---
; --- CHECKS THAT CX CHARACTERS STARTING AT DS:SI ARE ALL LETTERS
;     (A-Z, A-Z) OR SPACES. RETURNS AL = 1 IF SO (AND CX > 0),
;     AL = 0 OTHERWISE. ---
; --- WAITS FOR A KEYPRESS SO THE SCREEN DOESN'T FLY BY ---
CO_WAIT_KEY PROC NEAR
    LEA DX, PAUSE_MSG
    CALL PRINT_STRING
    MOV AH, 07H
    INT 21H
    RET
CO_WAIT_KEY ENDP

END
