; =================================================================
; LOGIN.ASM
;
; EVERYTHING ABOUT ACCOUNTS LIVES HERE:
;   - LOGGING IN WITH A USERNAME + PASSWORD
;   - REGISTERING A NEW ACCOUNT
;   - LOGGING OUT (CLEARING THE TYPED-IN USERNAME/PASSWORD SO THE
;     NEXT PERSON WHO SITS DOWN CAN'T SEE THEM)
;
; MAIN.ASM CALLS DO_LOGIN WHEN THE APP STARTS - THAT'S THE ONLY
; ENTRY POINT IT NEEDS. DO_LOGIN ITSELF SHOWS A SMALL "1.LOGIN /
; 2.REGISTER / 3.QUIT" MENU AND LOOPS THERE UNTIL A REAL LOGIN
; SUCCEEDS, AT WHICH POINT IT RETURNS AND MAIN.ASM TAKES OVER AND
; SHOWS THE FOOD-ORDERING MENU.
;
; HOW ACCOUNTS ARE STORED
; ------------------------
; THERE'S NO REAL DATABASE HERE - JUST ONE BIG BLOCK OF BYTES
; CALLED USER_DB, SPLIT INTO FIXED-SIZE "RECORDS" (ONE PER USER).
; EACH RECORD LOOKS LIKE THIS, BACK TO BACK:
;
;   [ USERNAME (21 BYTES) ][ PASSWORD (21 BYTES) ][ ADDRESS (31 BYTES) ][ DISCOUNT FLAG (1 BYTE) ]
;
; SO RECORD NUMBER 0 STARTS AT USER_DB+0, RECORD NUMBER 1 STARTS AT
; USER_DB+74, RECORD NUMBER 2 STARTS AT USER_DB+148, AND SO ON
; (74 = REC_SIZE, THE TOTAL WIDTH OF ONE RECORD - SEE THE EQUS
; BELOW). EVERY USERNAME/PASSWORD/ADDRESS IS STORED AS A NORMAL
; DOS STRING: THE REAL TEXT, THEN A '$' CHARACTER TO MARK THE END,
; THEN ZEROS TO PAD OUT TO THE FIXED WIDTH.
;
; THE "DISCOUNT FLAG" BYTE IS 1 IF THAT ACCOUNT'S SAVED ADDRESS IS
; CLOSE ENOUGH TO DELIGO TO GET THE 10% PROXIMITY DISCOUNT, OR 0 IF
; NOT. IT GETS SET ONCE, WHEN THE ACCOUNT REGISTERS (OR, FOR THE
; BUILT-IN ADMIN ACCOUNT, RIGHT HERE IN THE SEED DATA BELOW).
; =================================================================

.MODEL SMALL

; A TINY SHORTCUT SO WE DON'T HAVE TO WRITE THESE 3 LINES EVERY TIME
; WE WANT TO PRINT A '$'-TERMINATED STRING.
.DATA
    ; ---------- SIZES (CHANGE THESE HERE, NOTHING ELSE, IF THE LAYOUT EVER NEEDS TO GROW) ----------
    MAX_USERS   EQU 10                     ; HOW MANY ACCOUNTS WE CAN HOLD
    FIELD_LEN   EQU 21                     ; USERNAME/PASSWORD SLOT WIDTH (20 CHARS + '$')
    ADDR_LEN    EQU 31                     ; ADDRESS SLOT WIDTH (30 CHARS + '$')

    ADDR_OFFSET EQU FIELD_LEN*2            ; ADDRESS STARTS RIGHT AFTER USERNAME+PASSWORD
    DISC_OFFSET EQU ADDR_OFFSET + ADDR_LEN ; DISCOUNT FLAG STARTS RIGHT AFTER THE ADDRESS
    REC_SIZE    EQU DISC_OFFSET + 1        ; TOTAL WIDTH OF ONE WHOLE USER RECORD

    ; ---------- THE ACCOUNTS THEMSELVES ----------
    ; RECORD 0 IS THE BUILT-IN ADMIN ACCOUNT, SO THERE'S ALWAYS AT
    ; LEAST ONE WORKING LOGIN WITHOUT HAVING TO REGISTER FIRST.
    USER_DB     LABEL BYTE
                DB  'admin$', 15 DUP(0)                ; USERNAME (21 BYTES)
                DB  'pass123$', 13 DUP(0)               ; PASSWORD (21 BYTES)
                DB  '12 JALAN AMAN, KL$', 13 DUP(0)      ; ADDRESS  (31 BYTES) - ADMIN DEFAULTS TO KL
                DB  1                                    ; DISCOUNT FLAG - HARDCODED TO 1. THE ADMIN
                                                          ; ACCOUNT ALWAYS GETS THE 10% DISCOUNT, SAME
                                                          ; AS ADDRESS OPTIONS 1 AND 2 BELOW (SEE
                                                          ; CHOOSE_ADDRESS).
                DB  (MAX_USERS-1)*REC_SIZE DUP(0)        ; EMPTY ROOM FOR THE OTHER 9 ACCOUNTS
    USER_COUNT  DB  1                                    ; HOW MANY OF THE MAX_USERS SLOTS ARE FILLED

    ; ---------- THE CURRENTLY LOGGED-IN ACCOUNT ----------
    ; VALIDATE_LOGIN FILLS THESE IN THE MOMENT A LOGIN SUCCEEDS, BY
    ; COPYING THEM STRAIGHT OUT OF THAT ACCOUNT'S RECORD ABOVE. ANY
    ; OTHER MODULE (MENU.ASM, CHECKOUT.ASM) CAN READ THEM TO FIND
    ; OUT WHERE TO DELIVER AND WHETHER THE DISCOUNT APPLIES, WITHOUT
    ; EVER HAVING TO ASK THE USER AGAIN.
    CURRENT_ADDR      DB  ADDR_LEN DUP(0)   ; DELIVERY ADDRESS FOR THIS SESSION
    CURRENT_DISCOUNT  DB  0                 ; 1 = THIS SESSION GETS THE 10% DISCOUNT

    ; ---------- SCRATCH SPACE USED WHILE TYPING THINGS IN ----------
    INPUT_BUF     DB  22 DUP('$')   ; RAW DOS KEYBOARD-INPUT BUFFER (SEE READ_LINE)
    USER_INPUT    DB  21 DUP('$')   ; USERNAME TYPED AT THE LOGIN SCREEN
    PASS_INPUT    DB  21 DUP('$')   ; PASSWORD TYPED AT THE LOGIN SCREEN
    NEW_USER      DB  21 DUP('$')   ; USERNAME BEING CHOSEN WHILE REGISTERING
    NEW_PASS      DB  21 DUP('$')   ; PASSWORD BEING CHOSEN WHILE REGISTERING
    CONFIRM_PASS  DB  21 DUP('$')   ; PASSWORD TYPED A 2ND TIME, TO CHECK FOR TYPOS
    NEW_ADDR      DB  31 DUP('$')   ; ADDRESS CHOSEN WHILE REGISTERING
    NEW_DISCOUNT  DB  0             ; THAT ADDRESS'S DISCOUNT FLAG (0 OR 1) - HARDCODED
                                     ; BY CHOOSE_ADDRESS, NEVER CALCULATED

    ; ---------- THE 3 FIXED DELIVERY ADDRESSES OFFERED AT REGISTRATION ----------
    ; NO TABLES, NO INDEXING, NO MATH. EACH OPTION BELOW IS JUST WRITTEN
    ; OUT ON ITS OWN: ITS ADDRESS TEXT, AND A "SUFFIX" STRING THAT ALREADY
    ; HAS THE DISTANCE AND (WHERE IT APPLIES) THE "(10% OFF)" TAG TYPED
    ; STRAIGHT INTO IT. CHOOSE_ADDRESS BELOW JUST PRINTS ALL 3, ONE AFTER
    ; ANOTHER - IT DOES NOT LOOP OR CALCULATE ANYTHING.
    ;
    ; THE DISCOUNT RULE IS A HARDCODED FACT, NOT A CALCULATION:
    ;     OPTION 1 (12 JALAN AMAN, KL - 2KM)   -> 10% DISCOUNT
    ;     OPTION 2 (45 LORONG DAMAI, KL - 5KM) -> 10% DISCOUNT
    ;     OPTION 3 (7 TAMAN INDAH, JB - 8KM)   -> NO DISCOUNT
    ADDR1_TXT   DB  '12 JALAN AMAN, KL$'     ; OPTION 1 - SAVED TO NEW_ADDR IF CHOSEN
    ADDR2_TXT   DB  '45 LORONG DAMAI, KL$'   ; OPTION 2 - SAVED TO NEW_ADDR IF CHOSEN
    ADDR3_TXT   DB  '7 TAMAN INDAH, JB$'     ; OPTION 3 - SAVED TO NEW_ADDR IF CHOSEN

    ; THE NUMBER+DOT PRINTED BEFORE EACH ADDRESS, AND THE "(DISTANCE)
    ; (10% OFF)" TAIL PRINTED AFTER IT. JUST DISPLAY TEXT - NOTHING
    ; BELOW EVER GETS READ BACK OR COMPARED AGAINST.
    CA_LABEL_1  DB  '1. $'
    CA_LABEL_2  DB  '2. $'
    CA_LABEL_3  DB  '3. $'
    CA_SUFFIX_1 DB  ' (2KM) (10% OFF)',0DH,0AH,'$'
    CA_SUFFIX_2 DB  ' (5KM) (10% OFF)',0DH,0AH,'$'
    CA_SUFFIX_3 DB  ' (8KM)',0DH,0AH,'$'            ; NO "(10% OFF)" HERE - HARDCODED NO DISCOUNT

    ; ---------- SCREEN TEXT ----------
    WELCOME_MENU_MSG DB 0DH,0AH
                     DB '=============================================================',0DH,0AH
                     DB '     Welcome to DeliGo Food Delivery and Ordering System     ',0DH,0AH
                     DB '=============================================================',0DH,0AH
                     DB '1. Login',0DH,0AH
                     DB '2. Register',0DH,0AH
                     DB '3. Quit Program',0DH,0AH
                     DB '=============================================================',0DH,0AH
                     DB 'Choose an option: $'
    TITLE_MSG       DB  0DH,0AH,'-- LOGIN --',0DH,0AH,'$'
    REG_TITLE_MSG   DB  0DH,0AH,'-- NEW ACCOUNT REGISTRATION --',0DH,0AH,'$'

    PROMPT_USER     DB  0DH,0AH,'USERNAME : $'
    PROMPT_PASS     DB  0DH,0AH,'PASSWORD : $'
    REG_PROMPT_USER     DB  0DH,0AH,'CHOOSE A USERNAME : $'
    REG_PROMPT_PASS     DB  0DH,0AH,'CHOOSE A PASSWORD : $'
    REG_PROMPT_CONFIRM  DB  0DH,0AH,'CONFIRM PASSWORD  : $'
    REG_ADDR_TITLE      DB  0DH,0AH,'SELECT YOUR DELIVERY ADDRESS:',0DH,0AH,'$'
    REG_ADDR_CHOICE_MSG DB  0DH,0AH,'ENTER CHOICE (1-3): $'

    SUCCESS_MSG     DB  0DH,0AH,'LOGIN SUCCESSFUL! WELCOME.',0DH,0AH,'$'
    FAIL_MSG        DB  0DH,0AH,'INVALID USERNAME OR PASSWORD.',0DH,0AH,'$'
    LOGOUT_MSG      DB  0DH,0AH,'LOGGED OUT. GOODBYE!',0DH,0AH,'$'
    REG_DUP_MSG       DB  0DH,0AH,'USERNAME ALREADY TAKEN.',0DH,0AH,'$'
    REG_FULL_MSG      DB  0DH,0AH,'REGISTRATION IS FULL.',0DH,0AH,'$'
    REG_MISMATCH_MSG  DB  0DH,0AH,'PASSWORDS DO NOT MATCH.',0DH,0AH,'$'
    REG_SUCCESS_MSG   DB  0DH,0AH,'ACCOUNT CREATED! YOU CAN NOW LOG IN.',0DH,0AH,'$'
    INVALID_CHOICE_MSG DB 0DH,0AH,'INVALID CHOICE.',0DH,0AH,'$'
    NEWLINE         DB  0DH,0AH,'$'

.CODE
    PUBLIC DO_LOGIN, LOGOUT, CURRENT_ADDR, CURRENT_DISCOUNT
    ; SHARED HELPERS FROM TOOLS.ASM (SEE THAT FILE FOR WHAT EACH ONE DOES)
    EXTRN PRINT_STRING:NEAR, PRINT_CHAR:NEAR, CLEARSCREEN:NEAR
    EXTRN COPY_STRING:NEAR, CLEAR_BUF:NEAR, STR_COMPARE:NEAR
    ; MAIN.ASM SETS UP DS AND DRIVES THE POST-LOGIN MENU; ALL IT
    ; NEEDS FROM HERE IS DO_LOGIN (SHOWS THE LOGIN/REGISTER MENU
    ; AND ONLY RETURNS ONCE SOMEONE IS ACTUALLY LOGGED IN) AND
    ; LOGOUT. REGISTER IS ONLY EVER CALLED FROM DO_LOGIN ITSELF,
    ; SO IT DOESN'T NEED TO BE EXPORTED.

;-------------------------------------------------------------
; READ_LINE  -  READS ONE LINE OF NORMAL (VISIBLE) TEXT.
; IN:  DI = WHERE TO STORE IT
; USES DOS'S OWN BUFFERED-INPUT FUNCTION, THEN COPIES THE RESULT
; INTO DI AS A PLAIN '$'-TERMINATED STRING.
;-------------------------------------------------------------
READ_LINE PROC
    MOV INPUT_BUF[0], 20
    PUSH DI
    LEA DX, INPUT_BUF
    MOV AH, 0AH
    INT 21H
    POP DI
    MOV CL, INPUT_BUF[1]
    MOV CH, 0
    LEA BX, INPUT_BUF+2
    CMP CX, 0
    JE  RL_DONE
RL_LOOP:
    MOV AL, [BX]
    MOV [DI], AL
    INC BX
    INC DI
    LOOP RL_LOOP
RL_DONE:
    MOV BYTE PTR [DI], '$'
    RET
READ_LINE ENDP


;-------------------------------------------------------------
; READ_MASKED  -  READS A PASSWORD ONE KEY AT A TIME, ECHOING '*'
; INSTEAD OF THE REAL CHARACTER. BACKSPACE WORKS TOO.
; IN: DI = WHERE TO STORE IT
;-------------------------------------------------------------
READ_MASKED PROC
    XOR CX, CX
RM_LOOP:
    MOV AH, 08H
    INT 21H
    CMP AL, 0DH
    JE  RM_DONE
    CMP AL, 08H
    JE  RM_BACK
    CMP CX, 20
    JGE RM_LOOP
    MOV [DI], AL
    INC DI
    INC CX
    PUSH AX
    MOV DL, '*'
    CALL PRINT_CHAR
    POP AX
    JMP RM_LOOP
RM_BACK:
    CMP CX, 0
    JE  RM_LOOP
    DEC DI
    DEC CX
    MOV DL, 08H
    CALL PRINT_CHAR
    MOV DL, ' '
    CALL PRINT_CHAR
    MOV DL, 08H
    CALL PRINT_CHAR
    JMP RM_LOOP
RM_DONE:
    MOV BYTE PTR [DI], '$'
    LEA DX, NEWLINE
    CALL PRINT_STRING
    RET
READ_MASKED ENDP


;-------------------------------------------------------------
; STR_COMPARE  -  SI, DI = '$'-TERMINATED STRINGS. AL=1 IF EQUAL.
;
; ON PURPOSE, THIS USES DL (NOT BL) AS SCRATCH SPACE FOR THE
; CHARACTER IT'S CURRENTLY LOOKING AT. BX IS VERY OFTEN USED BY
; THE *CALLER* TO HOLD A POINTER (SEE FIND_USER BELOW, WHICH KEEPS
; A USER_DB RECORD ADDRESS IN BX ACROSS A CALL TO THIS ROUTINE) -
; BL IS JUST THE BOTTOM HALF OF BX, SO TOUCHING IT HERE WOULD
; SILENTLY CORRUPT THAT POINTER. DL DOESN'T HAVE THAT PROBLEM
; ANYWHERE IN THIS FILE.
;-------------------------------------------------------------

;-------------------------------------------------------------
; COPY_STRING  -  COPIES '$'-TERMINATED SI TO DI, INCLUSIVE
;-------------------------------------------------------------

;-------------------------------------------------------------
; CLEAR_BUF  -  DI=PTR, CX=COUNT. ZEROES CX BYTES AT DI.
;-------------------------------------------------------------

;-------------------------------------------------------------
; FIND_USER  -  SI = USERNAME TO SEARCH FOR ('$'-TERMINATED).
; RETURNS BX = MATCHING RECORD POINTER, OR 0 IF NOT FOUND.
; SHARED BY VALIDATE_LOGIN (LOGIN) AND REGISTER (DUP CHECK).
;-------------------------------------------------------------
FIND_USER PROC
    MOV CL, USER_COUNT
    MOV CH, 0
    LEA BX, USER_DB
    CMP CX, 0
    JE  FU_NOTFOUND
FU_LOOP:
    PUSH CX
    PUSH SI
    MOV DI, BX
    CALL STR_COMPARE
    POP SI
    POP CX
    CMP AL, 1
    JE  FU_FOUND
    ADD BX, REC_SIZE
    LOOP FU_LOOP
FU_NOTFOUND:
    XOR BX, BX
FU_FOUND:
    RET
FIND_USER ENDP


;-------------------------------------------------------------
; DO_LOGIN  -  MAIN.ASM'S ONLY WAY IN. FIRST SHOWS A SMALL
; "1.LOGIN / 2.REGISTER / 3.QUIT" MENU. PICKING REGISTER RUNS
; REGISTER (BELOW) AND THEN SHOWS THIS MENU AGAIN, SO A BRAND NEW
; ACCOUNT STILL HAS TO LOG IN LIKE ANYONE ELSE. PICKING LOGIN
; SHOWS THE ACTUAL USERNAME/PASSWORD SCREEN AND LOOPS THERE UNTIL
; A REAL ACCOUNT MATCHES, THEN RETURNS TO MAIN.ASM (WHICH TAKES
; OVER AND SHOWS THE FOOD-ORDERING MENU NEXT).
;-------------------------------------------------------------
DO_LOGIN PROC
DL_MENU:
    CALL CLEARSCREEN
    LEA DX, WELCOME_MENU_MSG
    CALL PRINT_STRING
    MOV AH, 01H
    INT 21H

    ; al  1 = 0?
    CMP AL, '1'
    JE  DL_DO_LOGIN
    CMP AL, '2'
    JE  DL_DO_REGISTER
    CMP AL, '3'
    JE  DL_QUIT

    LEA DX, NEWLINE               ; ANYTHING ELSE - JUST SHOW THE MENU AGAIN
    CALL PRINT_STRING
    JMP DL_MENU

DL_DO_REGISTER:
    CALL REGISTER
    JMP DL_MENU

DL_QUIT:
    MOV AX, 4C00H
    INT 21H

DL_DO_LOGIN:
LOGIN_LOOP:
    CALL CLEARSCREEN
    LEA DX, TITLE_MSG
    CALL PRINT_STRING
    LEA DX, PROMPT_USER
    CALL PRINT_STRING
    LEA DI, USER_INPUT
    CALL READ_LINE

    LEA DX, PROMPT_PASS
    CALL PRINT_STRING
    LEA DI, PASS_INPUT
    CALL READ_MASKED

    CALL VALIDATE_LOGIN
    CMP AL, 1
    JE  LOGIN_OK
    LEA DX, FAIL_MSG
    CALL PRINT_STRING
    JMP LOGIN_LOOP

LOGIN_OK:
    LEA DX, SUCCESS_MSG
    CALL PRINT_STRING
    RET
DO_LOGIN ENDP


;-------------------------------------------------------------
; VALIDATE_LOGIN  -  AL = 1 IF USER_INPUT/PASS_INPUT MATCH A RECORD.
; ON A MATCH, ALSO COPIES THAT ACCOUNT'S ADDRESS AND DISCOUNT FLAG
; INTO CURRENT_ADDR / CURRENT_DISCOUNT, SO THE REST OF THE PROGRAM
; KNOWS WHERE THIS ORDER SHOULD GO WITHOUT ASKING AGAIN.
;-------------------------------------------------------------
VALIDATE_LOGIN PROC
    LEA SI, USER_INPUT
    CALL FIND_USER
    CMP BX, 0
    JE  VL_FAIL

    LEA SI, PASS_INPUT
    MOV DI, BX
    ADD DI, FIELD_LEN
    CALL STR_COMPARE           ; AL = 1/0 - BX STILL POINTS AT THE RECORD
    CMP AL, 1
    JNE VL_FAIL

    ; --- REMEMBER THIS ACCOUNT'S ADDRESS + DISCOUNT FOR LATER ---
    MOV SI, BX
    ADD SI, ADDR_OFFSET
    LEA DI, CURRENT_ADDR
    CALL COPY_STRING

    MOV SI, BX
    ADD SI, DISC_OFFSET
    MOV AL, [SI]
    MOV CURRENT_DISCOUNT, AL

    MOV AL, 1
    RET

VL_FAIL:
    MOV AL, 0
    RET
VALIDATE_LOGIN ENDP


;-------------------------------------------------------------
; CHOOSE_ADDRESS  -  SHOWS THE 3 FIXED ADDRESSES (WITH DISTANCE,
; AND A "(10% OFF)" TAG ON THE ONES CLOSE ENOUGH TO THE STORE),
; THEN COPIES WHICHEVER ONE IS PICKED INTO NEW_ADDR / NEW_DISCOUNT
; FOR REGISTER TO SAVE INTO THE NEW ACCOUNT'S RECORD.
;-------------------------------------------------------------
CHOOSE_ADDRESS PROC
CA_SHOW_MENU:
    LEA DX, REG_ADDR_TITLE
    CALL PRINT_STRING

    ; ---- PRINT ALL 3 OPTIONS, ONE AFTER ANOTHER - NO LOOP ----
    LEA DX, CA_LABEL_1
    CALL PRINT_STRING
    LEA DX, ADDR1_TXT
    CALL PRINT_STRING
    LEA DX, CA_SUFFIX_1
    CALL PRINT_STRING

    LEA DX, CA_LABEL_2
    CALL PRINT_STRING
    LEA DX, ADDR2_TXT
    CALL PRINT_STRING
    LEA DX, CA_SUFFIX_2
    CALL PRINT_STRING

    LEA DX, CA_LABEL_3
    CALL PRINT_STRING
    LEA DX, ADDR3_TXT
    CALL PRINT_STRING
    LEA DX, CA_SUFFIX_3
    CALL PRINT_STRING

    LEA DX, REG_ADDR_CHOICE_MSG
    CALL PRINT_STRING
    MOV AH, 01H
    INT 21H

    ; ---- PLAIN IF / ELSE IF / ELSE ON THE TYPED CHARACTER - NO
    ;      ARITHMETIC ON IT, NO ARRAY, JUST 3 HARDCODED CASES ----
    CMP AL, '1'
    JNE CA_TRY_2
    LEA SI, ADDR1_TXT
    LEA DI, NEW_ADDR
    CALL COPY_STRING
    MOV NEW_DISCOUNT, 1          ; HARDCODED: OPTION 1 ALWAYS GETS 10% OFF
    JMP CA_CHOSEN

CA_TRY_2:
    CMP AL, '2'
    JNE CA_TRY_3
    LEA SI, ADDR2_TXT
    LEA DI, NEW_ADDR
    CALL COPY_STRING
    MOV NEW_DISCOUNT, 1          ; HARDCODED: OPTION 2 ALWAYS GETS 10% OFF
    JMP CA_CHOSEN

CA_TRY_3:
    CMP AL, '3'
    JNE CA_BAD                   ; NOT 1, 2 OR 3 - INVALID, SHOW MENU AGAIN
    LEA SI, ADDR3_TXT
    LEA DI, NEW_ADDR
    CALL COPY_STRING
    MOV NEW_DISCOUNT, 0          ; HARDCODED: OPTION 3 NEVER GETS A DISCOUNT
    JMP CA_CHOSEN

CA_CHOSEN:
    LEA DX, NEWLINE
    CALL PRINT_STRING
    RET

CA_BAD:
    LEA DX, NEWLINE
    CALL PRINT_STRING
    LEA DX, INVALID_CHOICE_MSG
    CALL PRINT_STRING
    JMP CA_SHOW_MENU
CHOOSE_ADDRESS ENDP


;-------------------------------------------------------------
; REGISTER  -  CREATES A NEW ACCOUNT: USERNAME, PASSWORD (TYPED
; TWICE TO CATCH TYPOS), THEN A DELIVERY ADDRESS FROM THE 3 FIXED
; CHOICES ABOVE.
;-------------------------------------------------------------
REGISTER PROC
REG_START:
    LEA DX, REG_TITLE_MSG
    CALL PRINT_STRING
    CMP USER_COUNT, MAX_USERS
    JL  REG_ROOM_OK
    LEA DX, REG_FULL_MSG
    CALL PRINT_STRING
    RET

REG_ROOM_OK:
    LEA DX, REG_PROMPT_USER
    CALL PRINT_STRING
    LEA DI, NEW_USER
    CALL READ_LINE

    LEA SI, NEW_USER
    CALL FIND_USER
    CMP BX, 0
    JNE REG_DUPLICATE
    JMP REG_READ_PASSWORD

REG_DUPLICATE:
    LEA DX, REG_DUP_MSG
    CALL PRINT_STRING
    JMP REG_START

REG_READ_PASSWORD:
    LEA DX, REG_PROMPT_PASS
    CALL PRINT_STRING
    LEA DI, NEW_PASS
    CALL READ_MASKED

    LEA DX, REG_PROMPT_CONFIRM
    CALL PRINT_STRING
    LEA DI, CONFIRM_PASS
    CALL READ_MASKED

    LEA SI, NEW_PASS
    LEA DI, CONFIRM_PASS
    CALL STR_COMPARE
    CMP AL, 1
    JE  REG_CHOOSE_ADDRESS
    LEA DX, REG_MISMATCH_MSG
    CALL PRINT_STRING
    JMP REG_READ_PASSWORD

REG_CHOOSE_ADDRESS:
    CALL CHOOSE_ADDRESS          ; FILLS IN NEW_ADDR AND NEW_DISCOUNT

    MOV AL, USER_COUNT
    MOV BL, REC_SIZE
    MUL BL
    LEA BX, USER_DB
    ADD BX, AX                   ; BX = WHERE THIS NEW RECORD STARTS

    MOV DI, BX
    LEA SI, NEW_USER
    CALL COPY_STRING              ; USERNAME
    MOV DI, BX
    ADD DI, FIELD_LEN
    LEA SI, NEW_PASS
    CALL COPY_STRING              ; PASSWORD
    MOV DI, BX
    ADD DI, ADDR_OFFSET
    LEA SI, NEW_ADDR
    CALL COPY_STRING              ; ADDRESS

    MOV DI, BX
    ADD DI, DISC_OFFSET
    MOV AL, NEW_DISCOUNT
    MOV [DI], AL                  ; DISCOUNT FLAG

    INC USER_COUNT
    LEA DX, REG_SUCCESS_MSG
    CALL PRINT_STRING
    RET
REGISTER ENDP


;-------------------------------------------------------------
; LOGOUT  -  SAYS GOODBYE AND WIPES THE TYPED-IN USERNAME/PASSWORD
; SO THE NEXT PERSON CAN'T SEE THEM.
;-------------------------------------------------------------
LOGOUT PROC
    LEA DX, LOGOUT_MSG
    CALL PRINT_STRING
    LEA DI, USER_INPUT
    MOV CX, 21
    CALL CLEAR_BUF
    LEA DI, PASS_INPUT
    MOV CX, 21
    CALL CLEAR_BUF
    RET
LOGOUT ENDP

END
