.MODEL SMALL

PUBLIC NEWLINE
PUBLIC CLEARSCREEN
PUBLIC READSTRING
PUBLIC READNUM
PUBLIC EXITPROGRAM
PUBLIC PRINT_STRING, PRINT_CHAR, PRINT_NUM
PUBLIC COPY_STRING, CLEAR_BUF, STR_COMPARE
PUBLIC CHECK_ALPHA, CHECK_DIGITS

.CODE

READSTRING PROC NEAR
    ; INPUT:
    ; DS:DX = ADDRESS OF DOS INPUT BUFFER
    ;
    ; BUFFER:
    ; BYTE 0 = MAXIMUM LENGTH
    ; BYTE 1 = ACTUAL LENGTH
    ; BYTE 2 ONWARD = ENTERED CHARACTERS
    ;
    ; ADDS '$' AFTER THE ENTERED TEXT.

    PUSH AX
    PUSH BX
    PUSH SI

    MOV BX,DX

    MOV AH,0AH
    INT 21H

    XOR AX,AX
    MOV AL,[BX+1]

    MOV SI,BX
    ADD SI,2
    ADD SI,AX

    MOV BYTE PTR [SI],'$'

    POP SI
    POP BX
    POP AX
    RET
READSTRING ENDP


READNUM PROC NEAR
    ; READS A POSITIVE DECIMAL NUMBER.
    ;
    ; OUTPUT:
    ; AX = ENTERED NUMBER

    PUSH BX
    PUSH CX
    PUSH DX

    XOR BX,BX

READNUMLOOP:
    MOV AH,01H
    INT 21H

    CMP AL,13
    JE READNUMDONE

    CMP AL,'0'
    JB READNUMLOOP

    CMP AL,'9'
    JA READNUMLOOP

    SUB AL,'0'

    XOR AH,AH
    MOV CX,AX

    MOV AX,BX
    MOV DX,10
    MUL DX

    ADD AX,CX
    MOV BX,AX

    JMP READNUMLOOP

READNUMDONE:
    MOV AX,BX

    POP DX
    POP CX
    POP BX
    RET
READNUM ENDP

NEWLINE PROC NEAR
    ; SAVING PREV REGISTERS TO JUMP BACK INTO
    PUSH AX
    PUSH DX

    ; PRINT INSTRUCTION
    MOV AH, 02H

    ; CARRIAGE RETURN
    MOV DL, 13
    INT 21H

    ; LINE FEED
    MOV DL,10
    INT 21H

    ; RETURN VALUES BACK
    POP DX
    POP AX
    RET
NEWLINE ENDP


; CLEARSCREEN  -  BLANKS THE WHOLE SCREEN AND PUTS THE CURSOR BACK
; AT THE TOP-LEFT CORNER, USING THE BIOS VIDEO INTERRUPT (INT 10H)
; INSTEAD OF PRINTING A SCREEN'S WORTH OF BLANK LINES OURSELVES.
CLEARSCREEN PROC NEAR

    ; SAVING PREV REGISTERS TO JUMP BACK INTO
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX

    ; BIOS FUNCTION 06H = "SCROLL WINDOW UP". AX=0600H WITH CX/DX
    ; COVERING THE WHOLE 80x25 SCREEN (CX=TOP-LEFT 0,0 - DX=BOTTOM-
    ; RIGHT 79,24, I.E. HEX 18,4F) MEANS "SCROLL THE ENTIRE SCREEN BY
    ; 0 LINES" - WHICH DOS TREATS AS "BLANK THE WHOLE THING". BH IS
    ; THE COLOUR (07H = LIGHT GREY ON BLACK) USED TO FILL IT.
    MOV AX,0600H
    MOV BH,07H
    MOV CX,0000H
    MOV DX,184FH
    INT 10H

    ; BIOS FUNCTION 02H = "SET CURSOR POSITION". DX=0000H MOVES THE
    ; CURSOR BACK TO ROW 0, COLUMN 0 (TOP-LEFT) SO THE NEXT THING
    ; PRINTED STARTS FROM A CLEAN SCREEN.
    MOV AH,02H
    MOV BH,00H
    MOV DX,0000H
    INT 10H

    POP DX
    POP CX
    POP BX
    POP AX
    RET
CLEARSCREEN ENDP


EXITPROGRAM PROC NEAR
    MOV AX,4C00H
    INT 21H
EXITPROGRAM ENDP

; =================================================================
; THE HELPERS BELOW ARE SHARED BY EVERY OTHER .ASM FILE IN THIS
; PROJECT - PRINTING TEXT/CHARACTERS/NUMBERS, COPYING OR CLEARING A
; '$'-TERMINATED STRING, COMPARING TWO OF THEM, AND CHECKING WHAT
; KIND OF CHARACTERS A TYPED-IN STRING CONTAINS. NOTHING HERE IS
; SPECIFIC TO LOGIN, CART, MENU OR CHECKOUT - THAT'S WHY THEY LIVE
; HERE INSTEAD OF BEING COPIED INTO EACH FILE THAT NEEDS THEM.
; =================================================================

PRINT_STRING PROC NEAR
    ; PRINTS A '$'-TERMINATED STRING.
    ; INPUT: DS:DX = ADDRESS OF THE STRING
    PUSH AX
    MOV AH, 09H
    INT 21H
    POP AX
    RET
PRINT_STRING ENDP


PRINT_CHAR PROC NEAR
    ; PRINTS ONE CHARACTER.
    ; INPUT: DL = THE CHARACTER
    PUSH AX
    MOV AH, 02H
    INT 21H
    POP AX
    RET
PRINT_CHAR ENDP


; PRINT_NUM  -  PRINTS THE 16-BIT NUMBER IN AX IN DECIMAL.
;
; THE TRICK: DIVIDING BY 10 REPEATEDLY GIVES YOU THE DIGITS BACKWARDS
; (THE REMAINDER EACH TIME IS THE *LAST* DIGIT - E.G. 123 / 10 = 12
; REMAINDER 3, SO '3' COMES OUT FIRST, THEN '2', THEN '1'). BUT A
; NUMBER HAS TO BE PRINTED FIRST-DIGIT-FIRST. SO EACH DIGIT IS PUSHED
; ONTO THE STACK AS IT'S FOUND (CONVERT_LOOP), THEN POPPED BACK OFF
; (PRINT_LOOP) - AND SINCE A STACK IS LAST-IN-FIRST-OUT, POPPING
; REVERSES THE ORDER A SECOND TIME, WHICH PUTS THE DIGITS BACK THE
; RIGHT WAY ROUND. CX COUNTS HOW MANY DIGITS WERE PUSHED, SO
; PRINT_LOOP KNOWS EXACTLY HOW MANY TO POP.
PRINT_NUM PROC NEAR
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX

    XOR CX, CX                 ; Digit counter = 0
    MOV BX, 10

CONVERT_LOOP:
    XOR DX, DX
    DIV BX                     ; Divide AX by 10 (Remainder in DX)
    PUSH DX                    ; Push remainder onto stack
    INC CX
    CMP AX, 0
    JNE CONVERT_LOOP

PRINT_LOOP:
    POP DX
    ADD DL, '0'                ; Convert digit to ASCII
    MOV AH, 02H
    INT 21H
    LOOP PRINT_LOOP

    POP DX
    POP CX
    POP BX
    POP AX
    RET
PRINT_NUM ENDP


COPY_STRING PROC
CS_LOOP:
    MOV AL, [SI]
    MOV [DI], AL
    INC SI
    INC DI
    CMP AL, '$'
    JE  CS_DONE
    JMP CS_LOOP
CS_DONE:
    RET
COPY_STRING ENDP


CLEAR_BUF PROC
    XOR AL, AL
CB_LOOP:
    MOV [DI], AL
    INC DI
    LOOP CB_LOOP
    RET
CLEAR_BUF ENDP


STR_COMPARE PROC
CMP_LOOP:
    MOV AL, [SI]
    MOV DL, [DI]
    CMP AL, DL
    JNE CMP_NOT_EQUAL
    CMP AL, '$'
    JE  CMP_EQUAL
    INC SI
    INC DI
    JMP CMP_LOOP
CMP_EQUAL:
    MOV AL, 1
    RET
CMP_NOT_EQUAL:
    MOV AL, 0
    RET
STR_COMPARE ENDP


CHECK_ALPHA PROC NEAR
    PUSH CX
    PUSH SI
    CMP CX, 0
    JE  CCA_BAD

CCA_LOOP:
    MOV AL, [SI]
    CMP AL, 'a'
    JB  CCA_CHECK_UPPER
    CMP AL, 'z'
    JBE CCA_OK_CHAR
    ; (falls through when AL > 'z' - not lowercase, so check uppercase next)

CCA_CHECK_UPPER:
    CMP AL, 'A'
    JB  CCA_SPACE
    CMP AL, 'Z'
    JBE CCA_OK_CHAR
    ; (falls through when AL > 'Z' - not a letter, so check for a space next)

CCA_SPACE:
    CMP AL, ' '
    JE  CCA_OK_CHAR
    JMP CCA_BAD

CCA_OK_CHAR:
    INC SI
    LOOP CCA_LOOP

    MOV AL, 1
    JMP CCA_DONE

CCA_BAD:
    MOV AL, 0

CCA_DONE:
    POP SI
    POP CX
    RET
CHECK_ALPHA ENDP


CHECK_DIGITS PROC NEAR
    PUSH CX
    PUSH SI
    CMP CX, 0
    JE  CCD_BAD

CCD_LOOP:
    MOV AL, [SI]
    CMP AL, '0'
    JB  CCD_BAD
    CMP AL, '9'
    JA  CCD_BAD
    INC SI
    LOOP CCD_LOOP

    MOV AL, 1
    JMP CCD_DONE

CCD_BAD:
    MOV AL, 0

CCD_DONE:
    POP SI
    POP CX
    RET
CHECK_DIGITS ENDP

END
